/**
 * constants/Countries.js
 *
 * All countries / territories for school sign-up (245 + "Other").
 * India first, then A–Z. The chosen country decides billing:
 *   IN  → 'legacy' (current Indian flow)
 *   any other code → 'subscription' (free trial – length set by the platform owner – then yearly plan)
 * The server makes the final decision (UserServiceApiController::registerTrialUser).
 *
 * Fields: code (ISO-3166 alpha-2), name, currency (ISO-4217), dial (country calling code).
 * keepLeadingZero: the local number's leading 0 is part of the number (Italy, San Marino,
 * Vatican) – it is NOT dropped when the dial code is added.
 * Dial codes from Google's libphonenumber data; currencies from ISO-4217 country mappings.
 */
export const COUNTRIES = [
  { code: "IN", name: "India", currency: "INR", dial: "+91" },
  { code: "AF", name: "Afghanistan", currency: "AFN", dial: "+93" },
  { code: "AX", name: "Åland Islands", currency: "EUR", dial: "+358" },
  { code: "AL", name: "Albania", currency: "ALL", dial: "+355" },
  { code: "DZ", name: "Algeria", currency: "DZD", dial: "+213" },
  { code: "AS", name: "American Samoa", currency: "USD", dial: "+1" },
  { code: "AD", name: "Andorra", currency: "EUR", dial: "+376" },
  { code: "AO", name: "Angola", currency: "AOA", dial: "+244" },
  { code: "AI", name: "Anguilla", currency: "XCD", dial: "+1" },
  { code: "AG", name: "Antigua and Barbuda", currency: "XCD", dial: "+1" },
  { code: "AR", name: "Argentina", currency: "ARS", dial: "+54" },
  { code: "AM", name: "Armenia", currency: "AMD", dial: "+374" },
  { code: "AW", name: "Aruba", currency: "AWG", dial: "+297" },
  { code: "AC", name: "Ascension Island", currency: "SHP", dial: "+247" },
  { code: "AU", name: "Australia", currency: "AUD", dial: "+61" },
  { code: "AT", name: "Austria", currency: "EUR", dial: "+43" },
  { code: "AZ", name: "Azerbaijan", currency: "AZN", dial: "+994" },
  { code: "BS", name: "Bahamas", currency: "BSD", dial: "+1" },
  { code: "BH", name: "Bahrain", currency: "BHD", dial: "+973" },
  { code: "BD", name: "Bangladesh", currency: "BDT", dial: "+880" },
  { code: "BB", name: "Barbados", currency: "BBD", dial: "+1" },
  { code: "BY", name: "Belarus", currency: "BYN", dial: "+375" },
  { code: "BE", name: "Belgium", currency: "EUR", dial: "+32" },
  { code: "BZ", name: "Belize", currency: "BZD", dial: "+501" },
  { code: "BJ", name: "Benin", currency: "XOF", dial: "+229" },
  { code: "BM", name: "Bermuda", currency: "BMD", dial: "+1" },
  { code: "BT", name: "Bhutan", currency: "BTN", dial: "+975" },
  { code: "BO", name: "Bolivia", currency: "BOB", dial: "+591" },
  { code: "BA", name: "Bosnia and Herzegovina", currency: "BAM", dial: "+387" },
  { code: "BW", name: "Botswana", currency: "BWP", dial: "+267" },
  { code: "BR", name: "Brazil", currency: "BRL", dial: "+55" },
  { code: "IO", name: "British Indian Ocean Territory", currency: "USD", dial: "+246" },
  { code: "VG", name: "British Virgin Islands", currency: "USD", dial: "+1" },
  { code: "BN", name: "Brunei", currency: "BND", dial: "+673" },
  { code: "BG", name: "Bulgaria", currency: "BGN", dial: "+359" },
  { code: "BF", name: "Burkina Faso", currency: "XOF", dial: "+226" },
  { code: "BI", name: "Burundi", currency: "BIF", dial: "+257" },
  { code: "KH", name: "Cambodia", currency: "KHR", dial: "+855" },
  { code: "CM", name: "Cameroon", currency: "XAF", dial: "+237" },
  { code: "CA", name: "Canada", currency: "CAD", dial: "+1" },
  { code: "CV", name: "Cape Verde", currency: "CVE", dial: "+238" },
  { code: "BQ", name: "Caribbean Netherlands", currency: "USD", dial: "+599" },
  { code: "KY", name: "Cayman Islands", currency: "KYD", dial: "+1" },
  { code: "CF", name: "Central African Republic", currency: "XAF", dial: "+236" },
  { code: "TD", name: "Chad", currency: "XAF", dial: "+235" },
  { code: "CL", name: "Chile", currency: "CLP", dial: "+56" },
  { code: "CN", name: "China", currency: "CNY", dial: "+86" },
  { code: "CX", name: "Christmas Island", currency: "AUD", dial: "+61" },
  { code: "CC", name: "Cocos (Keeling) Islands", currency: "AUD", dial: "+61" },
  { code: "CO", name: "Colombia", currency: "COP", dial: "+57" },
  { code: "KM", name: "Comoros", currency: "KMF", dial: "+269" },
  { code: "CD", name: "Congo (DRC)", currency: "CDF", dial: "+243" },
  { code: "CG", name: "Congo (Republic)", currency: "XAF", dial: "+242" },
  { code: "CK", name: "Cook Islands", currency: "NZD", dial: "+682" },
  { code: "CR", name: "Costa Rica", currency: "CRC", dial: "+506" },
  { code: "CI", name: "Côte d’Ivoire", currency: "XOF", dial: "+225" },
  { code: "HR", name: "Croatia", currency: "EUR", dial: "+385" },
  { code: "CU", name: "Cuba", currency: "CUP", dial: "+53" },
  { code: "CW", name: "Curaçao", currency: "ANG", dial: "+599" },
  { code: "CY", name: "Cyprus", currency: "EUR", dial: "+357" },
  { code: "CZ", name: "Czechia", currency: "CZK", dial: "+420" },
  { code: "DK", name: "Denmark", currency: "DKK", dial: "+45" },
  { code: "DJ", name: "Djibouti", currency: "DJF", dial: "+253" },
  { code: "DM", name: "Dominica", currency: "XCD", dial: "+1" },
  { code: "DO", name: "Dominican Republic", currency: "DOP", dial: "+1" },
  { code: "EC", name: "Ecuador", currency: "USD", dial: "+593" },
  { code: "EG", name: "Egypt", currency: "EGP", dial: "+20" },
  { code: "SV", name: "El Salvador", currency: "USD", dial: "+503" },
  { code: "GQ", name: "Equatorial Guinea", currency: "XAF", dial: "+240" },
  { code: "ER", name: "Eritrea", currency: "ERN", dial: "+291" },
  { code: "EE", name: "Estonia", currency: "EUR", dial: "+372" },
  { code: "SZ", name: "Eswatini", currency: "SZL", dial: "+268" },
  { code: "ET", name: "Ethiopia", currency: "ETB", dial: "+251" },
  { code: "FK", name: "Falkland Islands", currency: "FKP", dial: "+500" },
  { code: "FO", name: "Faroe Islands", currency: "DKK", dial: "+298" },
  { code: "FJ", name: "Fiji", currency: "FJD", dial: "+679" },
  { code: "FI", name: "Finland", currency: "EUR", dial: "+358" },
  { code: "FR", name: "France", currency: "EUR", dial: "+33" },
  { code: "GF", name: "French Guiana", currency: "EUR", dial: "+594" },
  { code: "PF", name: "French Polynesia", currency: "XPF", dial: "+689" },
  { code: "GA", name: "Gabon", currency: "XAF", dial: "+241" },
  { code: "GM", name: "Gambia", currency: "GMD", dial: "+220" },
  { code: "GE", name: "Georgia", currency: "GEL", dial: "+995" },
  { code: "DE", name: "Germany", currency: "EUR", dial: "+49" },
  { code: "GH", name: "Ghana", currency: "GHS", dial: "+233" },
  { code: "GI", name: "Gibraltar", currency: "GIP", dial: "+350" },
  { code: "GR", name: "Greece", currency: "EUR", dial: "+30" },
  { code: "GL", name: "Greenland", currency: "DKK", dial: "+299" },
  { code: "GD", name: "Grenada", currency: "XCD", dial: "+1" },
  { code: "GP", name: "Guadeloupe", currency: "EUR", dial: "+590" },
  { code: "GU", name: "Guam", currency: "USD", dial: "+1" },
  { code: "GT", name: "Guatemala", currency: "GTQ", dial: "+502" },
  { code: "GG", name: "Guernsey", currency: "GBP", dial: "+44" },
  { code: "GN", name: "Guinea", currency: "GNF", dial: "+224" },
  { code: "GW", name: "Guinea-Bissau", currency: "XOF", dial: "+245" },
  { code: "GY", name: "Guyana", currency: "GYD", dial: "+592" },
  { code: "HT", name: "Haiti", currency: "HTG", dial: "+509" },
  { code: "HN", name: "Honduras", currency: "HNL", dial: "+504" },
  { code: "HK", name: "Hong Kong", currency: "HKD", dial: "+852" },
  { code: "HU", name: "Hungary", currency: "HUF", dial: "+36" },
  { code: "IS", name: "Iceland", currency: "ISK", dial: "+354" },
  { code: "ID", name: "Indonesia", currency: "IDR", dial: "+62" },
  { code: "IR", name: "Iran", currency: "IRR", dial: "+98" },
  { code: "IQ", name: "Iraq", currency: "IQD", dial: "+964" },
  { code: "IE", name: "Ireland", currency: "EUR", dial: "+353" },
  { code: "IM", name: "Isle of Man", currency: "GBP", dial: "+44" },
  { code: "IL", name: "Israel", currency: "ILS", dial: "+972" },
  { code: "IT", name: "Italy", currency: "EUR", dial: "+39", keepLeadingZero: true },
  { code: "JM", name: "Jamaica", currency: "JMD", dial: "+1" },
  { code: "JP", name: "Japan", currency: "JPY", dial: "+81" },
  { code: "JE", name: "Jersey", currency: "GBP", dial: "+44" },
  { code: "JO", name: "Jordan", currency: "JOD", dial: "+962" },
  { code: "KZ", name: "Kazakhstan", currency: "KZT", dial: "+7" },
  { code: "KE", name: "Kenya", currency: "KES", dial: "+254" },
  { code: "KI", name: "Kiribati", currency: "AUD", dial: "+686" },
  { code: "XK", name: "Kosovo", currency: "EUR", dial: "+383" },
  { code: "KW", name: "Kuwait", currency: "KWD", dial: "+965" },
  { code: "KG", name: "Kyrgyzstan", currency: "KGS", dial: "+996" },
  { code: "LA", name: "Laos", currency: "LAK", dial: "+856" },
  { code: "LV", name: "Latvia", currency: "EUR", dial: "+371" },
  { code: "LB", name: "Lebanon", currency: "LBP", dial: "+961" },
  { code: "LS", name: "Lesotho", currency: "LSL", dial: "+266" },
  { code: "LR", name: "Liberia", currency: "LRD", dial: "+231" },
  { code: "LY", name: "Libya", currency: "LYD", dial: "+218" },
  { code: "LI", name: "Liechtenstein", currency: "CHF", dial: "+423" },
  { code: "LT", name: "Lithuania", currency: "EUR", dial: "+370" },
  { code: "LU", name: "Luxembourg", currency: "EUR", dial: "+352" },
  { code: "MO", name: "Macau", currency: "MOP", dial: "+853" },
  { code: "MG", name: "Madagascar", currency: "MGA", dial: "+261" },
  { code: "MW", name: "Malawi", currency: "MWK", dial: "+265" },
  { code: "MY", name: "Malaysia", currency: "MYR", dial: "+60" },
  { code: "MV", name: "Maldives", currency: "MVR", dial: "+960" },
  { code: "ML", name: "Mali", currency: "XOF", dial: "+223" },
  { code: "MT", name: "Malta", currency: "EUR", dial: "+356" },
  { code: "MH", name: "Marshall Islands", currency: "USD", dial: "+692" },
  { code: "MQ", name: "Martinique", currency: "EUR", dial: "+596" },
  { code: "MR", name: "Mauritania", currency: "MRU", dial: "+222" },
  { code: "MU", name: "Mauritius", currency: "MUR", dial: "+230" },
  { code: "YT", name: "Mayotte", currency: "EUR", dial: "+262" },
  { code: "MX", name: "Mexico", currency: "MXN", dial: "+52" },
  { code: "FM", name: "Micronesia", currency: "USD", dial: "+691" },
  { code: "MD", name: "Moldova", currency: "MDL", dial: "+373" },
  { code: "MC", name: "Monaco", currency: "EUR", dial: "+377" },
  { code: "MN", name: "Mongolia", currency: "MNT", dial: "+976" },
  { code: "ME", name: "Montenegro", currency: "EUR", dial: "+382" },
  { code: "MS", name: "Montserrat", currency: "XCD", dial: "+1" },
  { code: "MA", name: "Morocco", currency: "MAD", dial: "+212" },
  { code: "MZ", name: "Mozambique", currency: "MZN", dial: "+258" },
  { code: "MM", name: "Myanmar", currency: "MMK", dial: "+95" },
  { code: "NA", name: "Namibia", currency: "NAD", dial: "+264" },
  { code: "NR", name: "Nauru", currency: "AUD", dial: "+674" },
  { code: "NP", name: "Nepal", currency: "NPR", dial: "+977" },
  { code: "NL", name: "Netherlands", currency: "EUR", dial: "+31" },
  { code: "NC", name: "New Caledonia", currency: "XPF", dial: "+687" },
  { code: "NZ", name: "New Zealand", currency: "NZD", dial: "+64" },
  { code: "NI", name: "Nicaragua", currency: "NIO", dial: "+505" },
  { code: "NE", name: "Niger", currency: "XOF", dial: "+227" },
  { code: "NG", name: "Nigeria", currency: "NGN", dial: "+234" },
  { code: "NU", name: "Niue", currency: "NZD", dial: "+683" },
  { code: "NF", name: "Norfolk Island", currency: "AUD", dial: "+672" },
  { code: "KP", name: "North Korea", currency: "KPW", dial: "+850" },
  { code: "MK", name: "North Macedonia", currency: "MKD", dial: "+389" },
  { code: "MP", name: "Northern Mariana Islands", currency: "USD", dial: "+1" },
  { code: "NO", name: "Norway", currency: "NOK", dial: "+47" },
  { code: "OM", name: "Oman", currency: "OMR", dial: "+968" },
  { code: "PK", name: "Pakistan", currency: "PKR", dial: "+92" },
  { code: "PW", name: "Palau", currency: "USD", dial: "+680" },
  { code: "PS", name: "Palestine", currency: "ILS", dial: "+970" },
  { code: "PA", name: "Panama", currency: "PAB", dial: "+507" },
  { code: "PG", name: "Papua New Guinea", currency: "PGK", dial: "+675" },
  { code: "PY", name: "Paraguay", currency: "PYG", dial: "+595" },
  { code: "PE", name: "Peru", currency: "PEN", dial: "+51" },
  { code: "PH", name: "Philippines", currency: "PHP", dial: "+63" },
  { code: "PL", name: "Poland", currency: "PLN", dial: "+48" },
  { code: "PT", name: "Portugal", currency: "EUR", dial: "+351" },
  { code: "PR", name: "Puerto Rico", currency: "USD", dial: "+1" },
  { code: "QA", name: "Qatar", currency: "QAR", dial: "+974" },
  { code: "RE", name: "Réunion", currency: "EUR", dial: "+262" },
  { code: "RO", name: "Romania", currency: "RON", dial: "+40" },
  { code: "RU", name: "Russia", currency: "RUB", dial: "+7" },
  { code: "RW", name: "Rwanda", currency: "RWF", dial: "+250" },
  { code: "BL", name: "Saint Barthélemy", currency: "EUR", dial: "+590" },
  { code: "SH", name: "Saint Helena", currency: "SHP", dial: "+290" },
  { code: "KN", name: "Saint Kitts and Nevis", currency: "XCD", dial: "+1" },
  { code: "LC", name: "Saint Lucia", currency: "XCD", dial: "+1" },
  { code: "MF", name: "Saint Martin (French part)", currency: "EUR", dial: "+590" },
  { code: "PM", name: "Saint Pierre and Miquelon", currency: "EUR", dial: "+508" },
  { code: "VC", name: "Saint Vincent and the Grenadines", currency: "XCD", dial: "+1" },
  { code: "WS", name: "Samoa", currency: "WST", dial: "+685" },
  { code: "SM", name: "San Marino", currency: "EUR", dial: "+378", keepLeadingZero: true },
  { code: "ST", name: "São Tomé and Príncipe", currency: "STN", dial: "+239" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", dial: "+966" },
  { code: "SN", name: "Senegal", currency: "XOF", dial: "+221" },
  { code: "RS", name: "Serbia", currency: "RSD", dial: "+381" },
  { code: "SC", name: "Seychelles", currency: "SCR", dial: "+248" },
  { code: "SL", name: "Sierra Leone", currency: "SLE", dial: "+232" },
  { code: "SG", name: "Singapore", currency: "SGD", dial: "+65" },
  { code: "SX", name: "Sint Maarten", currency: "ANG", dial: "+1" },
  { code: "SK", name: "Slovakia", currency: "EUR", dial: "+421" },
  { code: "SI", name: "Slovenia", currency: "EUR", dial: "+386" },
  { code: "SB", name: "Solomon Islands", currency: "SBD", dial: "+677" },
  { code: "SO", name: "Somalia", currency: "SOS", dial: "+252" },
  { code: "ZA", name: "South Africa", currency: "ZAR", dial: "+27" },
  { code: "KR", name: "South Korea", currency: "KRW", dial: "+82" },
  { code: "SS", name: "South Sudan", currency: "SSP", dial: "+211" },
  { code: "ES", name: "Spain", currency: "EUR", dial: "+34" },
  { code: "LK", name: "Sri Lanka", currency: "LKR", dial: "+94" },
  { code: "SD", name: "Sudan", currency: "SDG", dial: "+249" },
  { code: "SR", name: "Suriname", currency: "SRD", dial: "+597" },
  { code: "SJ", name: "Svalbard and Jan Mayen", currency: "NOK", dial: "+47" },
  { code: "SE", name: "Sweden", currency: "SEK", dial: "+46" },
  { code: "CH", name: "Switzerland", currency: "CHF", dial: "+41" },
  { code: "SY", name: "Syria", currency: "SYP", dial: "+963" },
  { code: "TW", name: "Taiwan", currency: "TWD", dial: "+886" },
  { code: "TJ", name: "Tajikistan", currency: "TJS", dial: "+992" },
  { code: "TZ", name: "Tanzania", currency: "TZS", dial: "+255" },
  { code: "TH", name: "Thailand", currency: "THB", dial: "+66" },
  { code: "TL", name: "Timor-Leste", currency: "USD", dial: "+670" },
  { code: "TG", name: "Togo", currency: "XOF", dial: "+228" },
  { code: "TK", name: "Tokelau", currency: "NZD", dial: "+690" },
  { code: "TO", name: "Tonga", currency: "TOP", dial: "+676" },
  { code: "TT", name: "Trinidad and Tobago", currency: "TTD", dial: "+1" },
  { code: "TA", name: "Tristan da Cunha", currency: "SHP", dial: "+290" },
  { code: "TN", name: "Tunisia", currency: "TND", dial: "+216" },
  { code: "TR", name: "Turkey (Türkiye)", currency: "TRY", dial: "+90" },
  { code: "TM", name: "Turkmenistan", currency: "TMT", dial: "+993" },
  { code: "TC", name: "Turks and Caicos Islands", currency: "USD", dial: "+1" },
  { code: "TV", name: "Tuvalu", currency: "AUD", dial: "+688" },
  { code: "VI", name: "U.S. Virgin Islands", currency: "USD", dial: "+1" },
  { code: "UG", name: "Uganda", currency: "UGX", dial: "+256" },
  { code: "UA", name: "Ukraine", currency: "UAH", dial: "+380" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", dial: "+971" },
  { code: "GB", name: "United Kingdom", currency: "GBP", dial: "+44" },
  { code: "US", name: "United States", currency: "USD", dial: "+1" },
  { code: "UY", name: "Uruguay", currency: "UYU", dial: "+598" },
  { code: "UZ", name: "Uzbekistan", currency: "UZS", dial: "+998" },
  { code: "VU", name: "Vanuatu", currency: "VUV", dial: "+678" },
  { code: "VA", name: "Vatican City", currency: "EUR", dial: "+39", keepLeadingZero: true },
  { code: "VE", name: "Venezuela", currency: "VES", dial: "+58" },
  { code: "VN", name: "Vietnam", currency: "VND", dial: "+84" },
  { code: "WF", name: "Wallis and Futuna", currency: "XPF", dial: "+681" },
  { code: "EH", name: "Western Sahara", currency: "MAD", dial: "+212" },
  { code: "YE", name: "Yemen", currency: "YER", dial: "+967" },
  { code: "ZM", name: "Zambia", currency: "ZMW", dial: "+260" },
  { code: "ZW", name: "Zimbabwe", currency: "ZWL", dial: "+263" },
  { code: "ZZ", name: "Other country", currency: "USD", dial: "" },
];

export const findCountry = (code) => COUNTRIES.find(c => c.code === code) ?? null;

/** Best guess from the device time zone: India → "IN", otherwise "" (user must pick). */
export function guessCountryCode() {
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone || "";
    if (tz === "Asia/Kolkata" || tz === "Asia/Calcutta") return "IN";
  } catch {}
  return "";
}

/** Device IANA time zone (e.g. "Europe/London"), or "" if unavailable. */
export function deviceTimeZone() {
  try { return Intl.DateTimeFormat().resolvedOptions().timeZone || ""; } catch { return ""; }
}
