import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");
const isTablet = width >= 768;

export const Theme = {
  primary: "#2563eb",
  primaryDark: "#1d4ed8",
  accent: "#7c3aed",
  success: "#16a34a",
  danger: "#dc2626",
  text: "#0f172a",
  muted: "#64748b",
  placeholder: "#94a3b8",
  border: "#cbd5e1",
  card: "rgba(255,255,255,0.96)",
  pageGradient: ["#e0ecff", "#f8fbff", "#eef4ff"],
  brandGradient: ["#2563eb", "#1d4ed8", "#0f172a"],
  inputBg: "#f8fafc",
};

export const Layout = {
  isTablet,
  horizontalPadding: isTablet ? 60 : 20,
  cardWidth: isTablet ? "30%" : "48%",
};

export const AppStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f8fbff",
  },
  gradientBg: {
    flex: 1,
  },
  pageScrollContent: {
    flexGrow: 1,
    paddingHorizontal: isTablet ? 40 : 18,
    paddingTop: isTablet ? 28 : 16,
    paddingBottom: 40,
  },
  heroSection: {
    alignItems: "center",
    marginBottom: 14,
  },
  logoCircleSmall: {
    width: isTablet ? 78 : 66,
    height: isTablet ? 78 : 66,
    borderRadius: 40,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    shadowColor: "#1d4ed8",
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 7,
  },
  pageTitle: {
    fontSize: isTablet ? 28 : 14,
    fontWeight: "800",
    color: Theme.text,
    textAlign: "center",
    marginBottom: 6,
  },
  pageSubtitle: {
    fontSize: isTablet ? 15 : 10,
    color: Theme.muted,
    textAlign: "center",
    lineHeight: 20,
    maxWidth: 680,
  },
  card: {
    backgroundColor: Theme.card,
    borderRadius: 22,
    padding: isTablet ? 26 : 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    shadowColor: "#0f172a",
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 0 },
    elevation: 1,
  },
  cardTitle: {
    fontSize: isTablet ? 22 : 16,
    fontWeight: "700",
    color: Theme.text,
    marginBottom: 4,
  },
  cardSubtitle: {
    fontSize: 13,
    color: Theme.muted,
    marginBottom: 16,
  },
  fieldBlock: {
    marginBottom: 12,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Theme.inputBg,
    borderWidth: 1,
    borderColor: Theme.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    minHeight: isTablet ? 58 : 11,
    fontSize: isTablet ? 16 : 12,
  },
  selectWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Theme.inputBg,
    borderWidth: 1,
    borderColor: Theme.border,
    borderRadius: 14,
    paddingLeft: 14,
    minHeight: isTablet ? 58 : 30,
    fontSize: isTablet ? 16 : 12,
  },
  input: {
    flex: 1,
    color: Theme.text,
    fontSize: isTablet ? 16 : 14,
    paddingVertical: 14,
  },
  inputIcon: {
    marginRight: 10,
  },
  dateInput: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: Theme.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 15,
    backgroundColor: "#fff",
    marginBottom: 12,
  },
  actionButtonSecondary: {
    backgroundColor: Theme.accent,
    minHeight: 50,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  actionButtonText: {
    color: "#fff",
    fontWeight: "700",
    marginLeft: 8,
  },
  previewImage: {
    width: 140,
    height: 140,
    borderRadius: 16,
    marginTop: 14,
    alignSelf: "center",
  },
  imagePlaceholder: {
    marginTop: 14,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: Theme.border,
    borderRadius: 16,
    minHeight: 140,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Theme.inputBg,
  },
  placeholderText: {
    marginTop: 8,
    color: Theme.muted,
  },
  primaryActionButton: {
    backgroundColor: Theme.primary,
    minHeight: 56,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
    marginBottom: 30,
    shadowColor: Theme.primary,
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 5,
  },
  primaryActionText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 12,
    marginLeft: 8,
  },
  inlineCenter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  modalContainer: {
    backgroundColor: "#fff",
    margin: 20,
    borderRadius: 16,
    padding: 20,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 10,
    color: Theme.text,
  },
  modalButtonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  modalCancelText: {
    color: Theme.danger,
    fontWeight: "600",
  },
  modalConfirmText: {
    color: Theme.success,
    fontWeight: "700",
  },
  safeArea: {
    flex: 1,
    backgroundColor: "#f8fbff",
  },
  gradientBg: {
    flex: 1,
  },
  flexOne: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: "space-between",
    paddingHorizontal: isTablet ? 60 : 22,
    paddingVertical: isTablet ? 34 : 22,
  },

  // Top
  topSection: {
    alignItems: "center",
    marginTop: isTablet ? 20 : 10,
    marginBottom: 20,
  },
  logoOuter: {
    marginBottom: 16,
  },
  logoCircle: {
    width: isTablet ? 94 : 82,
    height: isTablet ? 94 : 82,
    borderRadius: 47,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#1d4ed8",
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 7,
  },
  appTitle: {
    fontSize: isTablet ? 30 : 16,
    fontWeight: "800",
    color: "#0f172a",
    textAlign: "center",
    marginBottom: 8,
  },
  appSubtitle: {
    fontSize: isTablet ? 16 : 12,
    color: "#475569",
    textAlign: "center",
    lineHeight: 22,
    maxWidth: isTablet ? 560 : "100%",
  },

  // Middle
  middleSection: {
    flex: 1,
    justifyContent: "center",
    marginVertical: 14,
  },
  loginCard: {
    backgroundColor: "rgba(255,255,255,0.95)",
    borderRadius: 22,
    padding: isTablet ? 30 : 22,
    shadowColor: "#0f172a",
    shadowOpacity: 0.1,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    maxWidth: isTablet ? 620 : "100%",
    alignSelf: "center",
    width: "100%",
  },
  cardHeader: {
    marginBottom: 18,
  },
  cardTitle: {
    fontSize: isTablet ? 28 : 16,
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: 6,
  },
  cardSubtitle: {
    fontSize: isTablet ? 15 : 14,
    color: "#64748b",
  },
  fieldBlock: {
    marginBottom: 10,
  },
  fieldLabel: {
    marginBottom: 7,
    color: "#334155",
    fontWeight: "600",
    fontSize: 12,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 14,
    paddingHorizontal: 14,
    minHeight: isTablet ? 58 : 52,
  },
  inputIcon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    color: "#0f172a",
    fontSize: isTablet ? 16 : 12,
    paddingVertical: 12,
  },
  actionRow: {
    alignItems: "flex-end",
    marginTop: 2,
    marginBottom: 18,
  },
  linkText: {
    color: "#2563eb",
    fontSize: 14,
    fontWeight: "600",
  },
  loginButton: {
    backgroundColor: "#2563eb",
    minHeight: 54,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    marginBottom: 18,
    shadowColor: "#2563eb",
    shadowOpacity: 0.24,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  loginButtonDisabled: {
    backgroundColor: "#7aa3f7",
  },
  loginButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  registerRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  registerText: {
    color: "#64748b",
    fontSize: 14,
  },
  registerLink: {
    color: "#2563eb",
    fontSize: 14,
    fontWeight: "700",
    textAlign: "center",
  },

  // Bottom
  bottomSection: {
    alignItems: "center",
    marginTop: 14,
    paddingBottom: 10,
  },
  versionText: {
    fontSize: 13,
    color: "#334155",
    fontWeight: "700",
    marginBottom: 8,
  },
  bottomSubText: {
    textAlign: "center",
    fontSize: 12,
    color: "#64748b",
    lineHeight: 18,
    maxWidth: isTablet ? 620 : "100%",
    marginBottom: 14,
  },
  featureRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 10,
  },
  featureBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#eff6ff",
    borderWidth: 1,
    borderColor: "#bfdbfe",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 7,
    marginHorizontal: 4,
    marginVertical: 4,
  },
  featureText: {
    color: "#1e3a8a",
    fontSize: 12,
    fontWeight: "600",
  },
   
});